apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-rollingupdate
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-rollingupdate
  template:
    metadata:
      labels:
        app: rollout-rollingupdate
    spec:
      containers:
        - name: rollouts-demo
          image: rkvishnu77/ai-planet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 10
        - setWeight: 50
        - pause:
            duration: 10
        - setWeight: 70
        - pause:
            duration: 10
        - setWeight: 100
