apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-react-app
  labels:
    app: todo-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-react-app
  template:
    metadata:
      labels:
        app: todo-react-app
    spec:
      containers:
      - name: todo-react-app
        image: docker.io/rkvishnu77/ai-planet:latest
        ports:
        - containerPort: 3000
