apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: ai-planet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: docker.io/rkvishnu77/ai-planet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
